version: "3.8"

services:
  # PostgreSQL Service
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - /mnt/storage/project1/pg_data:/var/lib/postgresql/data

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
      - AUTH_SECRET=vW+0xgP4aOp793Nq1/JqSu9LZW0i/LJhzzF7y5PFbA4=
    depends_on:
      - db
